baseURL = "https://www.aabsoo.com/"
languageCode = "en-us"
paginate = 6
theme = "portio"
title = "AABSOO"
# Main Menu

[[menu.main]]
name = "About"
url = "#about"
weight = 1
[[menu.main]]
name = "Service"
url = "#service"
weight = 2
[[menu.main]]
name = "Work"
url = "#work"
weight = 3
[[menu.main]]
name = "Learn"
url = "#learn"
weight = 4
[[menu.main]]
name = "Contact"
url = "#contact"
weight = 5

# Sitemap Menu
[[menu.sitemap]]
name = "About"
url = "about"
weight = 1
[[menu.sitemap]]
name = "Frequently Ask Question"
url = "#"
weight = 2
[[menu.sitemap]]
name = "Privacy & Policy"
url = "#"
weight = 3
[[menu.sitemap]]
name = "Blog"
url = "#"
weight = 4

[params]
blogPageURL = "blog"
contactLink = "contact"
copyright = "AABSOO 2022 © All rights reserved "
footerLogo = "images/contact/widget-logo.png"
formspreeURL = "YOUR FORMSPREE URL"
googleAnalytics = "YOUR GOOGLE ANALYTICS CODE"
logo = "images/site-navigation/logo.png"

[params.address]
address = "Heidelberg, Germany"
email = "contact@aabsoo.com"
phone = "+(49) 163 181 2981"



# Social icons
[[params.social]]
icon = "fa-instagram"
url = "https://www.instagram.com/aabsoo.farm"
weight = 1
[[params.social]]
icon = "fa-linkedin-square"
url = "https://www.linkedin.com/company/aabsoo/"
weight = 2
[[params.social]]
icon = "fa-youtube-square"
url = "https://www.youtube.com/watch?v=Bmq18RJ_K_c"
weight = 3

